#!/usr/bin/env python3
"""Build the newsletter digest HTML from analyzed JSON files.

Pairs `.tmp/emails/email_N.json` (for the Gmail message ID) with
`.tmp/analyzed/analyzed_N.json` (for the sender / summary / stats) and writes a
self-contained HTML file to `.tmp/newsletter_digest_YYYY-MM-DD.html`.

Usage (from workspace root):
    python3 .claude/skills/newsletter-digest/scripts/build_digest.py \\
        [--date YYYY-MM-DD] [--emails-dir DIR] [--analyzed-dir DIR] [--out PATH]
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import pathlib
import sys


def load_pairs(emails_dir: pathlib.Path, analyzed_dir: pathlib.Path):
    """Yield (analyzed_dict, gmail_message_id) pairs in order of email_N.json."""
    email_files = sorted(emails_dir.glob("email_*.json"))
    if not email_files:
        sys.exit(f"No email_*.json files found in {emails_dir}")

    for ef in email_files:
        stem = ef.stem.replace("email_", "")  # "01", "02", ...
        af = analyzed_dir / f"analyzed_{stem}.json"
        if not af.exists():
            print(f"  skip {ef.name}: no matching {af.name}", file=sys.stderr)
            continue
        email = json.loads(ef.read_text())
        analyzed = json.loads(af.read_text())
        yield analyzed, email.get("id", "")


def stats_cell(stats: list[str]) -> str:
    if not stats:
        return '<span style="color:#bdc1c6;font-style:italic;">—</span>'
    lis = "".join(f"<li>{html.escape(s)}</li>" for s in stats)
    return f"<ul>{lis}</ul>"


def build_row(analyzed: dict, msg_id: str) -> str:
    sender = html.escape(analyzed["sender"])
    summary_html = analyzed["summary_html"]  # pre-escaped by the analyzer subagent
    stats = stats_cell(analyzed.get("key_stats", []))
    gmail_link = f"https://mail.google.com/mail/u/0/#all/{msg_id}" if msg_id else "#"
    link = analyzed.get("original_link") or gmail_link
    return f"""      <tr>
        <td class="sender">{sender}</td>
        <td class="summary">{summary_html}</td>
        <td class="stats">{stats}</td>
        <td class="icon-cell"><a href="{html.escape(link)}" target="_blank">🔗</a></td>
        <td class="icon-cell"><a href="{gmail_link}" target="_blank">✉️</a></td>
      </tr>"""


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Newsletter Digest — {date}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; margin: 0; padding: 20px; background: #f8f9fa; color: #202124; }}
  .container {{ max-width: 1200px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); overflow: hidden; }}
  .header {{ background: #1a73e8; color: white; padding: 24px 32px; }}
  .header h1 {{ margin: 0; font-size: 22px; font-weight: 500; }}
  .header .subtitle {{ margin: 6px 0 0; opacity: 0.85; font-size: 14px; }}
  table {{ width: 100%; border-collapse: collapse; table-layout: fixed; }}
  col.col-sender {{ width: 10%; }}
  col.col-summary {{ width: 43%; }}
  col.col-stats {{ width: 40%; }}
  col.col-read {{ width: 3.5%; }}
  col.col-email {{ width: 3.5%; }}
  th {{ background: #f1f3f4; padding: 12px 16px; text-align: left; font-size: 14px; font-weight: 600; color: #5f6368; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e0e0e0; }}
  th.center {{ text-align: center; }}
  td {{ padding: 14px 16px; border-bottom: 1px solid #f1f3f4; vertical-align: top; font-size: 15px; line-height: 1.5; }}
  tr:hover td {{ background: #f8f9ff; }}
  .sender {{ font-weight: 600; color: #1a73e8; font-size: 15px; }}
  .summary {{ color: #3c4043; }}
  .summary ul {{ margin: 4px 0 0; padding-left: 18px; }}
  .summary li {{ margin-bottom: 4px; }}
  .stats {{ color: #5f6368; font-size: 14px; }}
  .stats ul {{ margin: 0; padding-left: 16px; }}
  .stats li {{ margin-bottom: 3px; }}
  .icon-cell {{ text-align: center; padding: 14px 4px; }}
  .icon-cell a {{ font-size: 20px; text-decoration: none; }}
  .footer {{ padding: 16px 32px; background: #f8f9fa; border-top: 1px solid #e0e0e0; font-size: 14px; color: #80868b; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Newsletter Digest — {date}</h1>
    <div class="subtitle">{count} newsletters · Past 24 hours</div>
  </div>
  <table>
    <colgroup>
      <col class="col-sender">
      <col class="col-summary">
      <col class="col-stats">
      <col class="col-read">
      <col class="col-email">
    </colgroup>
    <thead>
      <tr>
        <th>Sender</th>
        <th>Summary</th>
        <th>Key Statistics</th>
        <th class="center">🔗</th>
        <th class="center">✉️</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>
  <div class="footer">Generated by Claude AI · Newsletter Digest · {date}</div>
</div>
</body>
</html>
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--date", default=dt.date.today().isoformat())
    p.add_argument("--emails-dir", default=".tmp/emails")
    p.add_argument("--analyzed-dir", default=".tmp/analyzed")
    p.add_argument("--out", default=None, help="defaults to .tmp/newsletter_digest_<date>.html")
    args = p.parse_args()

    emails_dir = pathlib.Path(args.emails_dir)
    analyzed_dir = pathlib.Path(args.analyzed_dir)
    out_path = pathlib.Path(args.out or f".tmp/newsletter_digest_{args.date}.html")

    rows = []
    for analyzed, msg_id in load_pairs(emails_dir, analyzed_dir):
        rows.append(build_row(analyzed, msg_id))

    doc = TEMPLATE.format(date=args.date, count=len(rows), rows="\n".join(rows))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc)
    print(f"Wrote {out_path} ({len(doc)} chars, {len(rows)} newsletters)")


if __name__ == "__main__":
    main()
